- backend/spec/model_container_profile_spec.rb
- frontend/controllers/container_profiles_controller.rb
- frontend/locales/en.yml
- frontend/locales/enums/en.yml
- frontend/views/container_profiles/_toolbar.html.erb
- schemas/container_profile.rb
- yale_container_init.rb
This addresses outstanding issues with:
https://www.pivotaltracker.com/story/show/82360190
And tidies up a few translations along the way.
Now all fields except URI are required. And the dimension fields must be integers.
> Container profile validations

- backend/model/archival_object_ext.rb
- backend/model/mixins/archival_object_series.rb
- backend/model/top_container.rb
- backend/spec/model_yale_container_spec.rb
- frontend/controllers/top_containers_controller.rb
- frontend/routes.rb
- frontend/views/top_containers/_linker.html.erb
- indexer/indexer.rb
- schemas/archival_object_ext.rb
- schemas/top_container.rb
More for review, but dependent on the previous PR (#7)
> Scoped top container linking

- frontend/controllers/container_profiles_controller.rb
- frontend/views/container_profiles/_new.html.erb
- frontend/views/top_containers/_form.html.erb
Via the Container Profile linker
> [Delivers 84826138] Add ability to Create a Container Profile from the Top Container workflow

- frontend/views/top_containers/_form.html.erb
delivers 87422424 and 85393348 - two for one!
> make top container ils_item_id readonly in the frontend

- frontend/controllers/top_containers_controller.rb
- frontend/views/top_containers/bulk_operations/_browse.html.erb
- frontend/views/top_containers/bulk_operations/_results.html.erb
- frontend/views/top_containers/bulk_operations/_search_criteria.html.erb
- indexer/indexer.rb
- migrations/008_reindex_top_containers.rb
- remove Series criteria
- reword collection criteria to Resource/Accession
- index whether a top container has been exported and add Exported criteria
- also remove Edit/View actions from the results list when viewed via the linker browse
> [Delivers #82734844] Bulk selection criteria changes

- indexer/indexer.rb
- migrations/009_reindex_top_containers.rb
[Delivers 88044566]
Could it be this simple? Seems to work.
> Linked records in location view

- backend/model/container_profile.rb
- backend/spec/model_container_profile_spec.rb
- indexer/indexer.rb
- migrations/009_reindex_container_profiles.rb
> Container profile display string

- frontend/assets/top_containers.bulk.js
[fix for #82734936]
the bottom toolbar link wasn't working. now it does. hooray.
> fixed broken toolbar link for holding id update

- backend/controllers/container.rb
- backend/model/top_container.rb
- backend/spec/model_yale_container_spec.rb
- frontend/assets/top_containers.bulk.js
- frontend/controllers/top_containers_controller.rb
- frontend/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/views/top_containers/bulk_operations/_toolbar.html.erb
[delivers #82734896]
what it says.
> Bulk update container profile

- frontend/locales/en.yml
- frontend/views/top_containers/bulk_operations/_bulk_action_success.html.erb
- frontend/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/views/top_containers/bulk_operations/_collection_linker.html.erb
- frontend/views/top_containers/bulk_operations/_results.html.erb
- frontend/views/top_containers/bulk_operations/_search_criteria.html.erb
- frontend/views/top_containers/bulk_operations/_series_linker.html.erb
- frontend/views/top_containers/bulk_operations/_toolbar.html.erb
- First pass at adding I18n entries for obvious strings
> [Delivers #87164094] I18n all frontend strings

- backend/model/top_container.rb
- migrations/014_reindex_top_containers.rb
> changed top container long_display_string to show resource identifier not title

- backend/lib/aspace_json_to_yale_container_mapper.rb
- backend/lib/subcontainer_to_aspace_json_mapper.rb
- backend/lib/subcontainer_to_aspace_mapper.rb
- backend/model/instance_ext.rb
- backend/model/mixins/map_to_aspace_container.rb
- backend/model/top_container.rb
- backend/plugin_init.rb
- backend/spec/container_spec_helper.rb
- backend/spec/model_compatibility_spec.rb
- backend/spec/model_yale_container_spec.rb
Compatibility changes with the existing ArchivesSpace container model
> Container compatibility

- backend/lib/aspace_json_to_yale_container_mapper.rb
- backend/model/mixins/archival_object_series.rb
- backend/model/mixins/reindex_top_containers.rb
- backend/spec/container_spec_helper.rb
- backend/spec/model_yale_container_spec.rb
- frontend/controllers/top_containers_controller.rb
Also remove some unused code from the top_container_controller#typeahead as the uri coming in will never be an archival object uri.
> [Delivers #89131528] Add logic to check whether a topmost archival object is indeed a series

- backend/controllers/container.rb
- backend/model/top_container.rb
- backend/spec/model_yale_container_spec.rb
- frontend/assets/top_containers.bulk.js
- frontend/controllers/top_containers_controller.rb
- frontend/locales/en.yml
- frontend/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
- frontend/views/top_containers/bulk_operations/_toolbar.html.erb
[delivers #88512852]
adds an 'Update Locations' option to the 'Bulk Operations' dropdown.
> Bulk update location

- backend/lib/aspace_json_to_yale_container_mapper.rb
This is a fix for:
https://www.pivotaltracker.com/story/show/89253564
@marktriggs I'm not certain about this - fixed the immediate issue for me, but maybe there's more ... or less to it.
> skip digital_object instances when mapping

- backend/model/top_container.rb
- migrations/015_reindex_top_containers.rb
fix for:
https://www.pivotaltracker.com/story/show/89251778
> zap trailing colon in top container display string and reindex

- backend/lib/aspace_json_to_yale_container_mapper.rb
- backend/lib/container_management_migration.rb
- backend/model/mixins/reindex_top_containers.rb
A couple of changes to get the performance of the compatibility layer back up to scratch.
> Compat performance

- README.md
- backend/lib/aspace_json_to_yale_container_mapper.rb
- backend/lib/container_management_migration.rb
- migrations/019_index_topcontainer_fields.rb
> Existing container migration

- backend/lib/aspace_json_to_yale_container_mapper.rb
For review next week.  Starting the migration again today, so possibly more to come :)
> Some more container optimisations based on observing the AT migration.

- backend/lib/aspace_json_to_yale_container_mapper.rb
- backend/lib/container_management_migration.rb
- backend/spec/model_compatibility_spec.rb
> Container compatibility rule change

- frontend/locales/en.yml
- frontend/views/top_containers/_sidebar.html.erb
- frontend/views/top_containers/show.html.erb
With the addition of new sections to the readonly view for a top container it makes sense to now show a sidebar
> Add sidebar to TopContainer readonly view

- README.md
- backend/spec/container_spec_helper.rb
- lib/barcode_check.rb
doesn't really deliver any stories, but contributes to 86578804 and 90903398.
> Appconfig tweak and doco

- backend/model/extent_calculator.rb
> show container profile display string instead of name when calculating linear measure

- frontend/assets/top_containers.crud.js
- frontend/assets/top_containers.show.js
- frontend/assets/yale_containers.index.js
- frontend/views/top_containers/_new.html.erb
- frontend/views/top_containers/edit.html.erb
- frontend/views/top_containers/new.html.erb
- frontend/views/top_containers/show.html.erb
Replace //= javascript includes with actual &lt;script&gt; includes as they are not resolved when deployed with an ArchivesSpace build
> Fix Javascript includes

- frontend/locales/en.yml
- frontend/views/notes/_template_override.html.erb
Also add 'size' to the field so it displays all items upfront to the user.
> [Delivers #89470438] Add some inline help to describe how to use the multi-select field

- backend/lib/aspace_json_to_yale_container_mapper.rb
- backend/lib/container_management_migration.rb
- backend/spec/model_compatibility_spec.rb
New rule: search within the whole collection for an indicator.
> Compat rule changes 4

- frontend/assets/top_containers.bulk.js
> [Delivers #91110550] Handle alphas in the indicator e.g. 5a and ensure they follow the natural sort

- backend/lib/aspace_json_to_yale_container_mapper.rb
The AT migrator sends multiple locations attached to an accession as
containers with identical indicator_1 values but differing locations.
Despite the matching indicator, these really aren't referring to the
same container.
This addresses the discussion in https://www.pivotaltracker.com/n/projects/1205820/stories/85481460
> Split apart top containers for accessions in certain cases
