backend/model/archival_object_ext.rb
backend/model/container_profile.rb
backend/model/mixins/reindex_top_containers.rb
backend/model/top_container.rb
backend/spec/model_yale_container_spec.rb
frontend/views/top_containers/_new.html.erb
frontend/views/top_containers/edit.html.erb

When displaying labels for top containers, show some additional pieces of information:
* The container profile
* The series that the top container is connected to
Lots of fiddling to make sure it behaves properly even as archival objects are edited, moved around within trees, merged with other resources, transferred between repositories, etc. etc.

Unambigious display strings

---

frontend/views/top_containers/_linker.html.erb

Change the typeahead scope for the top container linker for an instance so that:
- new accession: scoped to repository
- existing accession: scoped to accession
- new resource: scoped to repository
- existing resource: scoped to entire resource hierarchy (resource and all archival object descendants)
- new archival object: scoped to entire resource hierarchy (resource and all archival object descendants)
- existing archival object: scoped to entire resource hierarchy (resource and all archival object descendants)

[Delivers #85393412] Change top container typeahead to scope within the resource hierarchy when there is one

---

backend/model/top_container.rb
indexer/indexer.rb
schemas/top_container.rb

...and allow these fields to be searched via a keyword search
Fields that can now be searched for via the text search include:
- Identifier of linked series
- top container display string
- accession identifiers
- resource identifiers
- location barcode
By also indexing permutations of the identifier, we also cover this requirement "We want to be able to search by collection ID and collection title. Whitespace and punctuation on collection ID should be trivial (MS.1642 and MS1642 should result in same results)".

[Delivers #82734844] Index permuations of a top container's linked record's identifier 

---

backend/model/top_container.rb
backend/spec/model_yale_container_spec.rb
frontend/assets/top_containers.bulk.js
frontend/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
frontend/views/top_containers/bulk_operations/_results.html.erb
frontend/views/top_containers/bulk_operations/_toolbar.html.erb
frontend/views/top_containers/index.html.erb
indexer/indexer.rb
schemas/top_container.rb

Format the bulk selection table based on the specified table columns: 
* Resource Identifier
* Resource Title
* The Component Unique Identifier for the highest ancestor component (this is because boxes often start over from 1 for each series -- we need the component identifier, like “Series 1” or “Accession 2015-A-005” in order to know which Box 1 we’re working with)
* Container profile name
* Container Number
* Barcode
* Location string
* Voyager Holdings Record Identifier value
* Restriction information
* Value of whether this container has been exported to Voyager (translate timestamp = present to yes)

[Delivers #82734794] Add new bulk selection table columns

---

backend/model/top_container.rb
frontend/controllers/top_containers_controller.rb
frontend/locales/en.yml
frontend/views/top_containers/_form.html.erb
lib/barcode_check.rb
yale_container_init.rb

config looks like this:
AppConfig[:yale_containers_barcode_length] = {
:system_default => {:min => 5, :max => 10},
:repository_2 => {:min => 8, :max => 12}
}
Some of the remaining ugliness arises from trying to give the user a hope of guessing how long her barcode can be. Alternative approaches welcome.

enforce barcode length limits as specified in config [delivers 82360390]

---

backend/model/top_container.rb
backend/spec/model_yale_container_spec.rb
frontend/assets/top_containers.bulk.js
frontend/controllers/top_containers_controller.rb
frontend/views/top_containers/bulk_operations/_browse.html.erb
frontend/views/top_containers/bulk_operations/_results.html.erb
indexer/indexer.rb
schemas/top_container.rb

From the pivotal comment: 
"We need additional ID and Titles to show up in the same row. Example: ID = MS-1234; Accession 2014;j MS-411, and Title = ArchivessSpace Committee records; accession title; ms-411 title."

[Delivers #82733622] Handle multiple linked records in the container display string

---

backend/controllers/container.rb
backend/model/top_container.rb
backend/spec/model_yale_container_spec.rb
frontend/assets/top_containers.bulk.js
frontend/controllers/top_containers_controller.rb
frontend/locales/en.yml
frontend/routes.rb
frontend/views/top_containers/_toolbar.html.erb
frontend/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
frontend/views/top_containers/bulk_operations/_search_criteria.html.erb
frontend/views/top_containers/bulk_operations/_toolbar.html.erb

[Delivers 84087370]
Supports deleting top container records individually, or in a bulk operation.
When a top container is deleted, all instances linked to it are also deleted.
There was also a request to delete top containers automatically when their last linking instance is deleted. This has not been implemented - see piv story for reasons.

Top container delete

---

frontend/assets/top_containers.bulk.css
frontend/assets/top_containers.bulk.js
frontend/views/top_containers/bulk_operations/_results.html.erb

After feedback requesting we reinstate the sorting by collection/series.  
This patch reintroduces the Resource/Accession and Series columns.  When a top container is linked to multiple collections/series only take the first entry when determining the sort order.  
For collections, sort is based on the first  identifier in the cell.  For series, sort is based on the first linked series' level and identifier combined.  This achieved with a custom textextraction configuration on the jquery tablesorter.

[Delivers #82734844] Reintroduce sorting of top containers by collection or series

---

backend/model/accession_ext.rb
backend/model/archival_object_ext.rb
backend/model/mixins/reindex_top_containers.rb
backend/model/mixins/rights_statement_restrictions.rb
backend/model/resource_ext.rb
backend/model/top_container.rb
backend/spec/factories.rb
backend/spec/model_yale_container_spec.rb
frontend/assets/top_containers.crud.js
frontend/locales/en.yml
frontend/views/top_containers/_form.html.erb
frontend/views/top_containers/show.html.erb
migrations/012_top_container_override_restricted.rb
schemas/top_container.rb

[Delivers 85393508]
-  Works out a top container's restricted status based on whether it has any contents that have an active rights statement whose date range includes today.
-  Allows the user to override this calculated value.
-  Shows the user any contents that are rights restricted.

Calculate container restriction

---

frontend/assets/top_containers.bulk.css
frontend/assets/top_containers.bulk.js
frontend/controllers/top_containers_controller.rb
frontend/views/top_containers/bulk_operations/_bulk_action_templates.html.erb
frontend/views/top_containers/bulk_operations/_results.html.erb

Adds some more data to the rapid entry form based on this requirement "As an archivist, when entering barcodes, I need to know the box number, associated series, and container profile type associated with that container to confirm that I am entering the proper barcode".
Also fix a bug whereby empty strings caused a uniqueness exception.  I know map all empty strings to `nil` so the barcode value is nulled.

Barcode Rapid Entry (take 2)

---

frontend/assets/top_containers.bulk.js

Only catch 'return' on keypress event so it tabs to the next input field (rather than jump fields as two events where catching the event previously)

[Delivers #82735468] Fix rapid barcode entry 'return' key skipping inputs

---

frontend/views/sub_containers/_show.html.erb

[possibly delivers #82734188]
this fixes a problem where if a subcontainer has no value for type_2, indicator_2, type_3 and indicator_3 then there is no room below the top container token for it to show its view button.
So if those fields are all blank then pad with a couple of brs :tongue:

pad the bottom of the sub container show template if type_2 etc are blank

---

frontend/controllers/top_containers_controller.rb

[fix for #89234060]
Now displays like this:
Barcode length for this repository: 9 characters
Instead of this:
Barcode length for this repository: 9-9 characters

fixed barcode range message for ranges of 1

---

indexer/indexer.rb
migrations/016_reindex_archival_objects_and_friends.rb

[fixes #88044566] ... yet again
This seemed like the cleanest way to ensure the aos, resources and accessions don't appear in the linked records section of the location view. Not sure how kosher it is.

remove location_uris from index for aos, resources and accessions

---

backend/model/top_container.rb
frontend/locales/en.yml
frontend/views/top_containers/_form.html.erb
frontend/views/top_containers/show.html.erb
migrations/015_top_container_legacy_restricted.rb
schemas/top_container.rb

[delivers #89016938]
the requirement changed - now legacy_restricted should be a boolean.
I left all of the old restricted stuff in there as it will probably be reused in some form when we redo this. Just commented out the UI bits and the one operation that is a bit expensive. Perhaps it's better to fully back this stuff out. Let me know if that is the preference.

Replace restricted boolean with enum

---

backend/model/resource_trees_ext.rb
backend/plugin_init.rb
frontend/views/archival_objects/_edit_inline.html.erb
frontend/views/resources/_edit_inline.html.erb

This patch overrides the ResourceTrees#set_node_instances to aggregate the sub container/top container data back on the tree node. And also override the _edit_inline.html.erb templates for Resource and Archival Object so they aggregate the new sub_container/top_container data correctly also.  
It'd be nice if this container data wasn't aggregated in multiple places!  But looking at the jstree/tree.js it's a bit of a mine field.  If we had some more time I think we could patch the core code to refresh the node completely via an AJAX call once the record had been saved so we could avoid building a fake node json in the edit_inline templates.  But this feels like days coding/testing.  :tired_face: 
And I know.. this solution is a little brute force.  I think we can sleep well knowing that …

[Delivers #89453818] fix container summary in tree view

---

backend/model/resource_trees_ext.rb
frontend/views/archival_objects/_edit_inline.html.erb
frontend/views/resources/_edit_inline.html.erb

.. when there is no barcode.  Reformat the string to optionally display the barcode if it is present and look like this 'Container: <indicator> [<barcode>]'.

[Delivers #89711490] Fix empty brackets in the tree's container summary 

---

migrations/018_add_suppressed_to_rlshp_tables.rb

[kind of a fix for #89734308]
Anything with an instance was blowing up in public. The reason was the relationship mixin wanting to call suppressed on the relationship classes. So I added it and now it's happy.
I guess we never saw this because we're always admin ;)

added a suppressed column to the rlshp tables

---

backend/model/mixins/reindex_top_containers.rb
frontend/controllers/top_containers_controller.rb
frontend/locales/en.yml
frontend/views/top_containers/bulk_operations/_search_criteria.html.erb
indexer/indexer.rb
migrations/019_reindex_top_containers.rb

[fixes #84087370]
We need a way of deleting empty top containers. This achieves that by adding a filter to the top container search form for empty containers. It is then possible to delete them via the delete bulk operation.

add support for finding empty top containers

---

frontend/controllers/top_containers_controller.rb
indexer/indexer.rb

Padded a sort field to 255 places to sort correctly by numbers where
they're present.

Sort the typeahead dropdown by the top container's indicator

---

frontend/locales/en.yml

[requested for #84087370]
just changes the label for the empty filter to "Unassociated containers"
... probably should have just committed this to master - never mind.

changed label for empty filter

---

backend/controllers/container_profile.rb
backend/plugin_init.rb
frontend/controllers/container_profiles_controller.rb
frontend/locales/en.yml
frontend/views/container_profiles/_toolbar.html.erb
frontend/views/top_containers/_toolbar.html.erb
migrations/022_rename_container_profile_permission.rb

This new permission is derived from the global permission for managing container profiles and allows the admin to assign it to groups etc.

Introduce a repository scoped permission for container profiles

---

frontend/assets/top_containers.show.js
frontend/views/top_containers/show.html.erb
indexer/indexer.rb
migrations/023_reindex_records_linked_to_top_containers.rb

Index any linked top_container uris against the records they link to and then show the embedded search on the readonly top container show template.
Note: after merge there may be a migration conflict with other PRs???

[Delivers #89918068] show linked records on top container view

---

backend/model/top_container.rb
backend/spec/model_yale_container_spec.rb
frontend/assets/top_containers.crud.js
frontend/locales/en.yml
frontend/views/top_containers/_form.html.erb
frontend/views/top_containers/bulk_operations/_results.html.erb
migrations/027_backout_old_rights_implementation.rb
schemas/top_container.rb

Including top_container fields 'restricted', 'override_restricted' and 'rights_restricted_contents'.
On the top container bulk operations listing, I've replaced the 'Restricted' column with 'Legacy Restricted' as we don't currently index the calculated active restrictions.  These active restrictions are calculated upon sequel_to_json on the top container every time it is read -- while we could index it, we would need to ensure the linked records cause the top containers to reindex correctly when updates/deletes/moves/transfers came in.

Backout old restriction implementation

---

frontend/views/top_containers/_form.html.erb

... in the top container form but retain the value by including it as a hidden input.
This complements Mark's migration mapping to bring across the legacy userdefinedbool for this field.

[Delivers #89470628] Don't allow editing of the legacy_restricted field 

---

backend/model/accession_ext.rb
backend/model/mixins/reindex_top_containers.rb
backend/model/resource_ext.rb
migrations/028_reindex_top_containers.rb

and fix a bug where digital object instances weren't handled
[fixes #91108110]
This feels a little icky.

rejig the ReindexTopContainers mixin for use by accessions and resources

---

backend/lib/aspace_json_to_managed_container_mapper.rb
backend/model/ead_model_ext.rb
backend/model/ead_serializer_ext.rb
backend/model/mixins/converter_extra_container_values.rb
backend/model/mixins/ead_converter_ext.rb
backend/model/mixins/export_helpers_ext.rb
backend/model/mixins/resolve_child_containers_for_export.rb
backend/model/mixins/serialize_extra_container_values.rb
schemas/container_ext.rb

Implement these rules in the plugin EAD converter/serializer:
- *Include top_container barcodes as part of &lt;container/&gt; in EAD export (use the label attribute for barcodes)*
We extend `EADSerializer` with a new mixin `SerializeExtraContainerValues` that appends the barcode to the container label attribute surrounded by brackets e.g. "Audio [1112233]" where "Audio" is the instance type.
- *Use barcodes in &lt;container/&gt; to map top_containers as part of EAD import*
We extend `EADConverter` with a new mixin `ConverterExtraContainerValues` that parses out the barcode (within the brackets of the label attribute) and set this on the container so it will be mapped to a top container.
- *Include top_container container profile nicknames (or URL, if present) as part of &lt;container/&gt; …

[Delivers #92615858] Extend EAD import/export to handle container things

---

frontend/assets/extent_calculator.js

Discovered when testing v1.2.0 compatible version with the Dartmouth data.
To replicate:
1. Have heaps of extent types so that the dropdown is replaced with a typeahead combobox (more than 50)
2. Calculate Extent
3. Select a Type in the Extent form
4 . "Create Extent"
5. The resulting Extent subrecord doesn't have type set

Fix extent type not setting correctly when the <select> has been replaced with a combobox
